// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClIYUZey29Iwv3HQ_1woECnNK0mRnv6nA',
    appId: '1:945933242150:web:a7c65547baa4a8e2d3fbe7',
    messagingSenderId: '945933242150',
    projectId: 'newsapp-e9741',
    authDomain: 'newsapp-e9741.firebaseapp.com',
    storageBucket: 'newsapp-e9741.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkAFsQVggAgp8ZadjWWWF_oFmN7rxpjaE',
    appId: '1:945933242150:android:38ec8366f4a05586d3fbe7',
    messagingSenderId: '945933242150',
    projectId: 'newsapp-e9741',
    storageBucket: 'newsapp-e9741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCndMjLClaqc7bSGO0tVjJcrl8IpSz6sHU',
    appId: '1:945933242150:ios:176dce2b8969a901d3fbe7',
    messagingSenderId: '945933242150',
    projectId: 'newsapp-e9741',
    storageBucket: 'newsapp-e9741.appspot.com',
    iosClientId: '945933242150-n4btg8ovhfurpotvpaiotjkhavdhkkve.apps.googleusercontent.com',
    iosBundleId: 'com.example.dainikUjala',
  );
}
